### ISSUE TITLE
Wait for the next Ionic CLI release to use this template by running `ionic start mySuperApp super`

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic-starter-super#106]
@danielsogl 
From here: https://github.com/driftyco/ionic-starter-super/commit/43d6d53aa3a9c47077874843c7e4699de34967e2

Please specify the version and expected release date.

**Comment by danielsogl** [comment]
Hey @peterennis, we will add the CLI command soon. But this issue has nothing to do with the repo itself because the CLI downloads always the master branch so we don't specify versions for our templates.

If you want to test it our, download the ionic2-app-base repo and copy the starter-super files into the same folder. Run npm install and that's it.

**Comment by piotrowski** [comment]
Until then it already works perfectly fine with Ionic CLI 2.2.3 where `starter` is still a valid starter template, so you can run the exact command from the Readme.

I expect Ionic v3 CLI will piggyback this change with their next minor release.

**Comment by nebur395** [comment]
I just reinstalled Ionic framework and running the `ionic info` command I obtained this output:  

**global packages:**
```
  @ionic/cli-utils : 1.0.0
  Ionic CLI        : 3.0.0
```
**System**
....

So I conclude that the CLI version you need (3.0.0 +) has already arrived.

**Comment by piotrowski** [comment]
No, 3.0.0 removed the starter template temporarily :/ A later version will add it back.
For now you have to use 2.2.3 if you want to automatically install the super starter.

**Comment by danielsogl** [comment]
I close this issue. We added the super template back to the CLI 3. You are able to use it with the next release.
