### ISSUE TITLE
Use translation service or limit number of translations

### ISSUE THREAD

**Issue by AndreasGassmann** [driftyco/ionic-starter-super#47]
There are now quite a few languages in this project. I feel like maintaining the translations when adding new content will be quite difficult and result in a lot of inconsistencies in the translation files.

So my suggestion would be to either
- use a service like https://weblate.org/en/ to manage the translations
- or limit the number of the translations to english and another language (maybe spanish or german), just to illustrate how the ng2-translate module works

Any thoughts on this?

**Comment by abennouna** [comment]
ng2-translate handles missing translation keys by falling back to the default language. I believe such inconsistencies do not make the app unusable, and the contributors can update the i18n files smoothly.

We could also add a simple MissingTranslationHandler implementation in order to highlight such missing keys in console or view.

**Comment by danielsogl** [comment]
Hey @AndreasGassmann, feel free to create a PR with a new language.

**Comment by AndreasGassmann** [comment]
My question was not about adding a new language but about how to manage the translations. But I'll take that as a no.

**Comment by piotrowski** [comment]
@AndreasGassmann Is there a free translation hosting provider that works with Github by default? Then maybe it would make sense to integrate this. Does Weblate?

Otherwise I think the super start should be fine with manual PRs if someone notices missing translations in his language or is missing his language.

**Comment by AndreasGassmann** [comment]
It looks like weblate does, but you have to contact them first: https://weblate.org/en-gb/hosting/

But thinking about it, it's probably too much effort to set everything up compared to the relatively small benefit it brings.

**Comment by piotrowski** [comment]
Well, it doesn't hurt to learn about new stuff. I contacted them, let's see how this works out. Maybe it is awesome and should be recommended for all translations that have to be kept up to date.

**Comment by AndreasGassmann** [comment]
I've used weblate before (self-hosted). It works very well. I would probably create a new "weblate" branch that you can push to and pull from inside weblate and then merge it back to master when new translations are available.
