### ISSUE TITLE
deviceready did not fire within 2000ms

### ISSUE THREAD

**Issue by dodopok** [driftyco/ionic-starter-super#64]
Running android native, it takes too long between a white screen and the app (after the splashscreen):

Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.

**Comment by wbhob** [comment]
My recommendation would be to hide the splash screen a few ms after your `constructor(){}` is called in `app.component.ts`. Either way, this is more of a Cordova issue, not Ionic. Also, it has no effect on your actual app; I get this error all the time, as do many other developers, so you have to find a way around because you can't make it any faster 😄 

Good luck!

**Comment by mlynch** [comment]
Just pushed a fix to ionic-native to increase this delay for sanity. Otherwise I don't believe this is an issue in this repo so I will close. Thanks.
